USE Master

DROP TABLE IF EXISTS Aflevering;
DROP TABLE IF EXISTS Film;
DROP TABLE IF EXISTS Serie;
DROP TABLE IF EXISTS KijkGedrag;
DROP TABLE IF EXISTS Programma;
DROP TABLE IF EXISTS Profiel;
DROP TABLE Abonnement;

